# Generated by Django 5.0.4 on 2024-04-30 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0004_blog_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='blog_uploaded_pics/'),
        ),
    ]
